<a href="https://colab.research.google.com/github/SUKstudent/Infotact_Data_Analytics_Internship/blob/lonali-ray/notebooks/EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries loaded successfully")

Libraries loaded successfully

In [8]:
from google.colab import files
uploaded = files.upload()

Saving multi_touch_attribution_data.csv to multi_touch_attribution_data.csv

In [9]:
df = pd.read_csv('multi_touch_attribution_data.csv')

print("Dataset Shape:", df.shape)
df.head()

Dataset Shape: (10000, 5)

   User ID            Timestamp         Channel            Campaign Conversion
0    83281  2025-02-10 07:58:51           Email  New Product Launch         No
1    68071  2025-02-10 23:38:48      Search Ads         Winter Sale         No
2    90131  2025-02-11 10:41:07    Social Media     Brand Awareness        Yes
3    71026  2025-02-10 08:19:44  Direct Traffic                   -        Yes
4    94486  2025-02-10 15:15:46           Email         Retargeting        Yes

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   User ID     10000 non-null  int64
 1   Timestamp   10000 non-null  object
 2   Channel     10000 non-null  object
 3   Campaign    10000 non-null  object
 4   Conversion  10000 non-null  object
dtypes: int64(1), object(4)
memory usage: 390.8+ KB

In [11]:
df.isnull().sum()

User ID       0
Timestamp     0
Channel       0
Campaign      0
Conversion    0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.describe(include='all')

            User ID            Timestamp         Channel Campaign Conversion
count   10000.00000                10000           10000    10000      10000
unique          NaN                 9737               6        6          2
top             NaN  2025-02-11 20:29:26  Direct Traffic        -         No
freq            NaN                    3            1721     3131       5056
mean    54957.01700                  NaN             NaN      NaN        NaN
std     25685.14741                  NaN             NaN      NaN        NaN
min     10028.00000                  NaN             NaN      NaN        NaN
25%     32391.00000                  NaN             NaN      NaN        NaN
50%     55446.00000                  NaN             NaN      NaN        NaN
75%     77298.00000                  NaN             NaN      NaN        NaN
max     99995.00000                  NaN             NaN      NaN        NaN

In [14]:
df['Channel'].value_counts()

Channel
Direct Traffic    1721
Referral          1685
Display Ads       1669
Social Media      1662
Email             1654
Search Ads        1609
Name: count, dtype: int64

In [16]:
df['Conversion'].value_counts()

Conversion
No     5056
Yes    4944
Name: count, dtype: int64