<a href="https://colab.research.google.com/github/SUKstudent/Infotact_Data_Analytics_Internship/blob/lonali-ray/notebooks/metric_data_modelling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving multi_touch_attribution_dataset_cleaned.csv to multi_touch_attribution_dataset_cleaned.csv

In [ ]:
df=pd.read_csv("/content/multi_touch_attribution_dataset_cleaned.csv")

In [ ]:
total_spend = df['ad_spend'].sum()
total_revenue = df['conversion_value'].sum()

print("Total Spend:", round(total_spend))
print("Total Revenue:", round(total_revenue0))

Total Spend: 1921
Total Revenue: 61087

In [ ]:
converted_customers = df[df['converted'] == 1]['user_id'].nunique()

print("Converted Customers:", converted_customers)

Converted Customers: 209

In [ ]:
cac = total_spend / converted_customers

print("Customer Acquisition Cost:", round(cac,2))

Customer Acquisition Cost: 9.19

In [ ]:
roas = total_revenue / total_spend

print("ROAS:", round(roas,2))

ROAS: 31.8

In [ ]:
channel_spend = df.groupby('channel')['ad_spend'].sum().sort_values(ascending=False)

channel_spend

channel
Google Ads        723.08
LinkedIn Ads      685.33
Meta Ads          401.32
TikTok Ads        101.07
Email              10.14
Direct              0.00
Organic Search      0.00
Referral            0.00
Name: ad_spend, dtype: float64

In [ ]:
channel_revenue = df.groupby('channel')['conversion_value'].sum().sort_values(ascending=False)

channel_revenue

channel
Google Ads        19152.57
Direct            15021.46
Email             12322.49
Organic Search     7363.02
LinkedIn Ads       4825.41
TikTok Ads         1081.29
Referral            722.89
Meta Ads            597.62
Name: conversion_value, dtype: float64

In [ ]:
channel_roas = (
    df.groupby('channel')
      .agg(
          Total_Spend=('ad_spend','sum'),
          Revenue=('conversion_value','sum')
      )
)

channel_roas['ROAS'] = channel_roas['Revenue'] / channel_roas['Total_Spend']

channel_roas.sort_values('ROAS', ascending=False)

                Total_Spend   Revenue         ROAS
channel
Direct                 0.00  15021.46          inf
Organic Search         0.00   7363.02          inf
Referral               0.00    722.89          inf
Email                 10.14  12322.49  1215.235700
Google Ads           723.08  19152.57    26.487484
TikTok Ads           101.07   1081.29    10.698427
LinkedIn Ads         685.33   4825.41     7.041002
Meta Ads             401.32    597.62     1.489136

In [ ]:
dim_channel = df[['channel']].drop_duplicates().reset_index(drop=True)

dim_channel['channel_id'] = range(1, len(dim_channel)+1)

dim_channel

          channel  channel_id
0      TikTok Ads           1
1  Organic Search           2
2          Direct           3
3        Meta Ads           4
4    LinkedIn Ads           5
5           Email           6
6      Google Ads           7
7        Referral           8

In [ ]:
dim_campaign = df[['campaign']].drop_duplicates().reset_index(drop=True)

dim_campaign['campaign_id'] = range(1, len(dim_campaign)+1)

dim_campaign

                 campaign  campaign_id
0           creator_spark            1
1            how_to_guide            2
2            direct_visit            3
3             retargeting            4
4         decision_makers            5
5          interest_stack            6
6          abandoned_cart            7
7           trial_nurture            8
8            brand_search            9
9       competitor_search           10
10   high_intent_keywords           11
11        software_review           12
12         affiliate_blog           13
13             saved_link           14
14             newsletter           15
15               seo_blog           16
16              b2b_leads           17
17             saas_trial           18
18        comparison_page           19
19         lookalike_1pct           20
20               ugc_demo           21
21  short_video_awareness           22
22              typed_url           23
23           partner_site           24

In [ ]:
dim_user = df[['user_id']].drop_duplicates()

dim_user

     user_id
0     U00001
4     U00002
9     U00003
10    U00004
14    U00005
...      ...
1909  U00496
1911  U00497
1917  U00498
1921  U00499
1922  U00500

[500 rows x 1 columns]

In [ ]:
df['event_date'] = pd.to_datetime(df['event_date'])

dim_date = pd.DataFrame()

dim_date['event_date'] = df['event_date'].drop_duplicates()

dim_date['year'] = dim_date['event_date'].dt.year
dim_date['month'] = dim_date['event_date'].dt.month
dim_date['day'] = dim_date['event_date'].dt.day

dim_date

    event_date  year  month  day
0   2026-02-05  2026      2    5
1   2026-02-07  2026      2    7
2   2026-02-08  2026      2    8
4   2026-03-10  2026      3   10
5   2026-03-11  2026      3   11
..         ...   ...    ...  ...
495 2026-03-20  2026      3   20
507 2026-03-01  2026      3    1
603 2026-01-04  2026      1    4
822 2026-05-05  2026      5    5
932 2026-05-04  2026      5    4

[125 rows x 4 columns]

In [ ]:
fact_marketing = df[[
    'user_id',
    'channel',
    'campaign',
    'event_date',
    'ad_spend',
    'conversion_value',
    'converted'
]]

fact_marketing.head()

,user_id,channel,campaign,event_date,ad_spend,conversion_value,converted
0,U00001,TikTok Ads,creator_spark,2026-02-05,0.20,0.00,0
1,U00001,Organic Search,how_to_guide,2026-02-07,0.00,0.00,0
2,U00001,Direct,direct_visit,2026-02-08,0.00,0.00,0
3,U00001,Meta Ads,retargeting,2026-02-08,0.62,267.15,1
4,U00002,LinkedIn Ads,decision_makers,2026-03-10,3.75,0.00,0